add `audio-stream` file, without test
decentraland/scene-explorer-tests pull request #8
Opened 2023-12-18 22:10 UTC by sdilauro

2023-12-19 16:29 UTC, leanmendoza requested changes

2023-12-19 16:29 UTC, leanmendoza commented on screenshot/godot_snapshot_mesh_renderer_box.png
Copy the snapshot obtained by running with `--rendering-driver opengl3", these snapshot shouldn't be modified

2023-12-19 16:29 UTC, leanmendoza commented on screenshot/godot_snapshot_ui_dropdown_red.png
Is the half-screen gradient intentional?

2023-12-19 16:29 UTC, leanmendoza commented on src/tests/audio-stream/index.test.ts
Add `// TODO:` when something is incomplete or it needs to be reviewed again in the future

2023-12-19 16:29 UTC, leanmendoza commented on src/tests/audio-stream/index.test.ts
In this case, this is not being imported, so it doesn't anything, better to comment the entire file

2023-12-19 16:29 UTC, leanmendoza commented on src/tests/avatar-attach/index.test.ts
Add a `TODO` => this is being tested by hiding the primary player avatar, so not properly tested I think

2023-12-19 16:29 UTC, leanmendoza commented on src/tests/ui-background/index.test.tsx
> +  // console.log("asd")
```suggestion
```
dead code

2023-12-19 16:29 UTC, leanmendoza commented on src/tests/ui-background/index.test.tsx
> +function getScreenCanvasInfo(): { w: number; h: number } {
add TODO

2023-12-19 16:29 UTC, leanmendoza commented on src/tests/ui-button/index.test.tsx
> +function getScreenCanvasInfo(): { w: number; h: number } {
export this to a ui-utils.ts and re use it

2023-12-19 16:29 UTC, leanmendoza commented on src/tests/ui-button/index.test.tsx
> +// import { UiCanvasInformation, engine } from '@dcl/sdk/ecs'
dead code

2023-12-19 17:25 UTC, sdilauro commented on screenshot/godot_snapshot_ui_dropdown_red.png
No, the test changes the walls' color, and the walls are affected by environmental lighting

2023-12-19 17:35 UTC, sdilauro commented on screenshot/godot_snapshot_mesh_renderer_box.png
the command `cargo run --rendering-driver opengl3` should work? because it throw:

> error: Found argument 'rendering-driver' which wasn't expected, or isn't valid in this context

2023-12-21 18:26 UTC, leanmendoza approved these changes

2023-12-21 18:27 UTC, merged